resources:
  pipelines:
    metadata_pipeline:
      name: metadata_pipeline
      catalog: metadata_governance
      target: bronze
      serverless: true
      libraries:
       - notebook:
          path: ../src/pipeline/bronze_layer.py
       - notebook:
          path: ../src/pipeline/silver_layer.sql
       - notebook:
          path: ../src/pipeline/gold_layer.py
      configuration:
        source_path: /Volumes/metadata_governance/bronze/raw_data/
      continuous: false
      development: false
